#cloud-config
# You will need to edit this file before creating your new servers
users:
  - name: web
    primary_group: web
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:

packages:
  - ripgrep
  - rsync
  - nginx
  - ufw

runcmd:
  - sed -i 's/^#\(Storage=auto\)/\1/' /etc/systemd/journald.conf
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - systemctl restart ssh
  - systemctl restart systemd-journald
  - sudo ufw allow from 203.0.113.0/24 to any port 22
  - sudo ufw deny from 203.1.113.4
  - sudo ufw default deny incoming
  - sudo ufw default allow outgoing
  - sudo ufw allow ssh
  - sudo ufw allow 22
  - sudo ufw allow http 
  - sudo ufw enable 